# Build settings
markdown: kramdown
permalink: pretty


# Site settings
title: GDG DevFest Istanbul 2014
email: info@gdgistanbul.com
description: "GDG DevFest - the biggest Google related event in Turkey"
baseurl: ""
url: "http://devfesttr.com/"
permalink: /blog/:title
googleAnalyticsTrackingId: "UA-41931868-1"
googleAnalyticsSiteUrl: "devfesttr.com"

# Conference Location block
eventLocationName: "Üsküdar Bağlarbaşı Kültür Merkezi"
eventLocationAddress: "Selamiali Mh Eski Bağlarbaşı İETT garajı Bağlarbaşı Üsküdar, İstanbul"
eventStartTime: "2014-10-18T09:00"
eventStartTimeHumanReadable: "09:00"
eventEndTime: "2014-10-18T20:00"
eventEndTimeHumanReadable: "20:00"
eventPlaceCoordinates: "41.02385, 29.031556"
mapCenterCoordinates: "41.02385, 29.031556"
mapMobileCenterCoordinates: "41.02385, 29.031556"

# Logistics Location Block
logisticsMapCenterCoordinates: "41.02385,29.031556"
logisticsMapMobileCenterCoordinates: "41.02385,29.031556"

# Subscribe
subscribeAction: "http://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"

# Documents
c4pUrl: "http://goo.gl/6du2Z4"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, istanbul, devfestist, devfesttr"
twitterAccount: "@GDGIstanbul"
socialImageSrc: "/img/hero.jpg"

# Header
eventDate: "October 18, İstanbul"
typeoutTextValues: '"", "Conference", "Workshops", "Hackathon", "İstanbul"'

# About Event Block
eventName: "GDG DevFest İstanbul"

# Team Block
aboutUs: Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences.

# Speakers List Block
showSessions: false
thumbnailsFolder: /img/speakers/

# Footer
gplusFollowUsUrl: "https://plus.google.com/+Gdgistanbul"
twitterFollowUsUrl: "https://twitter.com/intent/user?screen_name=GDGIstanbul"
fbFollowUsUrl: "https://facebook.com/Google"

# Blog
blogCommentsEnabled: true
discusShortName: "devfestist"
