# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENCE.txt', 'CNAME']


# Site Settings
title: "GDG DevFest Trabzon 2014"
email: "info@gdgtrabzon.com"
description: "GDG DevFest - the Google related event in Turkey"
baseurl: ""
url: "http://devfesttrabzon.com/"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-70420458-1"
googleAnalyticsSiteUrl: "devfesttrabzon.com"

# Organizer Info
organizerName: "GDG Trabzon"
organizerAlternateName: "Google Developer Group Trabzon"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "info@gdgtrazon.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://gdgtrabzon.com/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, trabzon, devfesttrabzon"
twitterAccount: "@GDGTrabzon"
socialImageSrcGooglePlus: "/img/seo/social_logo.png"
socialImageSrcTwitter: "/img/seo/social_logo.png"
socialImageSrcFacebook: "/img/seo/social_logo.png"


# Documents
#c4pUrl: "http://www.meetup.com/MineCraft-Istanbul/events/213563482/"
#c4sponsorsUrl: "/assets/devfest2014.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
# - {permalink: "/schedule/", text: "Schedule"}
# - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/#partners", text: "Sponsors"}
 - {permalink: "/organizers", text: "Organizers"}
 - {permalink: "/logistics/", text: "Logistics"}
# - {link: "http://2013.devfesttr.com", text: "DevFest'13"}
# - {link: "http://wtm14.devfesttr.com", text: "DevFest Women'14"}
#bottomNavigationLinks:
# - {link: "http://www.meetup.com/MineCraft-Istanbul/events/213563482/", text: "Minecraft Workshop"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "GDG DevFest<typeout>2014"
eventDate: "6 December, 2014"
typeoutTextValues: '"", "Conference", "Workshops", "Trabzon"'
typeoutFallback: "Season"
#heroButtons:
# - {link: "http://www.meetup.com/MineCraft-Istanbul/events/213563482/", text: "Minecraft Workshop"}
# - {permalink: "/#tickets", text: "Register to event"}

# About Block
aboutTitle: "About GDG DevFest"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "The biggest Google related developer event in Istanbul carefully crafted for you by GDG community! Awesome speakers and lot's of fun! This time, right in the heart of Trabzon!" }
 - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
# - {title: "Minecraft Workshop", image: "minecraft.png", text: "Are you or your kids into Minecraft? Did you know you can learn to mod it with Java and NetBeans IDE?" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "1600", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "24", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
 - {count: "42", specialCharacter: "", info: "speakers", detail: "The answer to life, the universe and everything"}
 - {count: "5", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
#rockstarSpeakersImage: "rockstar-speakers.jpg"
#rockstarSpeakersCount: 4
#rockstarSpeakersTitle: "Rockstar speakers"
#rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Prof. Dr. Osman Turan Culture and Congress Center"
eventStreetAddress: "Karadeniz Teknik Üniversitesi, Trabzon"
eventAddressLocality: "Trabzon"
eventAddressLocalityRegion: "Ortahisar"
eventAddressCountry: "Turkey"
eventStartTime: "2014-12-06T09:00"
eventDoorTime: "09:00"
eventEndTime: "2014-12-06T20:00"
eventPlaceCoordinates: "40.9986541, 39.7647572"
mapCenterCoordinates: "40.9986541, 39.7647572"
mapMobileCenterCoordinates: "40.9986541, 39.7647572"

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "devfest"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=900"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Tickets Block
#ticketsTitle: "Please Register"
#ticketsOffers:
# -
#  name: "Free Ticket"
#  buyButtonLink: "http://devfesttr14.eventbrite.com"
#  buyButtonText: "Register"
#  validFrom: "2014-12-06T10:00"
#  validThrough: "2014-12-06T23:59"
# -
#  name: "Minecraft Hacking Workshop for KIDs"
#  buyButtonLink: "http://www.meetup.com/MineCraft-Istanbul/events/213563482/"
#  buyButtonText: "Register"
#  validFrom: "2014-12-06T10:00"
#  validThrough: "2014-12-06T23:59"

# Footer
socialLinks:
 - {link: "https://plus.google.com/+GDGTrabzon", icon: "google-plus"}
 - {link: "https://twitter.com/GDGTrabzon", icon: "twitter"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://gdgtrabzon.com", text: "GDG Trabzon"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:info@gdgtrabzon.com", text: "info@gdgtrabzon.com"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: false
discusShortName: "devfestist"

# Speakers List Block
showSessions: false

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "40.9986541, 39.7647572"
logisticsMapMobileCenterCoordinates: "40.9986541, 39.7647572"

# Logistics Direction Details Block
directionDetailsImage: "backgroundtrbzn1.jpg"
directionDetailsTitle: "Get around Trabzon"
directionDetailsCards:
# - {title: "From the Airport", information: 'Airport is easily reachable by public transport. You can either take subway train or look for busses called "HAVATAŞ". More information is available at <a href="http://www.ataturkairport.com/en-EN/Transportation/pages/airporttrasnportation.aspx">airport website</a>.'}
# - {title: "Public Transit", information: 'You can either take subway train or look for busses called "HAVATAŞ". More information will be provided here to directly go to the venue.'}
# - {title: "Hotels", information: 'Trabzon has lots of great hotels and hostels. More information will be available later.'}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: false

# Hackathon About Block
aboutHackathonTitle: "Minecraft Workshop"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Istanbul"
hackathonAddressLocalityRegion: "Uskudar"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Turkey"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
